#!/bin/sh /etc/rc.common
# Starting gsdevice service to remotly manage i2c relay

USE_PROCD=1
START=99
STOP=15

start_service() {
        echo start
        # commands to launch application
        procd_open_instance
        procd_set_param command /opt/goswitch/gsdevice "/opt/goswitch/config/device.json"
        procd_set_param user root
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}

stop() {
        echo stop
        # commands to kill application
}
